#!/usr/bin/env bash
# Run Nginx as Nginx
chmod 755 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/g" /etc/nginx/nginx.conf
chown -R nginx:nginx /etc/nginx
su nginx -c "service nginx restart"
